### **Machine Learning Zoomcamp**
#### **1.7 Introduction to NumPy**
Plan:
- Creating arrays
- Multi-dementional arrays 
- Randomly generated arrays 
- Element-wise operations 
    - Comparison operations
     - Logical operations
- Summarizing operations

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from 'C:\\Users\\Daiyaan\\AppData\\Roaming\\Python\\Python38\\site-packages\\numpy\\__init__.py'>

#### **Creating arrays**

In [2]:
# array create with zeroes size 10
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
# array create with ones size 10
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
# array create with arbitrary numbers size 10 and element 2.5
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [5]:
a = np.array([1, 2, 3, 5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

In [6]:
# access element from array
a[2]

3

In [7]:
# using assignment operator
a[2] = 10

In [8]:
a

array([ 1,  2, 10,  5,  7, 12])

In [9]:
# create arange function
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [11]:
# create linspace function
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

### **Multi-dimensional arrays**

In [12]:
# create an array 5 rows and 2 columns
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

In [15]:
# access element from array
n[0, 1]

2

In [16]:
# assignment operator
n[0, 1] = 20

In [17]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [18]:
# assignment operator
n[2] = [1, 1, 1]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [19]:
# if we get fist column
n[:, 1]

array([20,  5,  1])

In [23]:
# get all rows
n[:]

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [21]:
# if we get last column
n[:, 2]

array([3, 6, 1])

In [22]:
# assignment operator last column of 2 dimensional arrays
n[:, 2] = [0, 1, 2]
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

### **Randomly generated array**

In [23]:
## random array generated
np.random.rand(5,2)

array([[0.59239455, 0.96663895],
       [0.78295465, 0.19992568],
       [0.56660465, 0.26767161],
       [0.49032979, 0.4164161 ],
       [0.57128086, 0.00932583]])

In [25]:
## fixing random numbers and get same results
np.random.seed(2)

## random array generated
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [26]:
# standard uniform distribution n is normal
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [27]:
# multiply every element by 100
np.random.seed(2)
100 * np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [28]:
# generating random integers 5 rows and 2 columns
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

### **Element-wise operations**  

In [29]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [30]:
# add a number to array
a + 1

array([1, 2, 3, 4, 5])

In [31]:
# multiply by a number
a * 2

array([0, 2, 4, 6, 8])

In [32]:
# divide by a number
a / 100

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [33]:
10 + (a * 2)

array([10, 12, 14, 16, 18])

In [34]:
# take a power
(10 + (a * 2)) ** 2

array([100, 144, 196, 256, 324])

In [35]:
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [36]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [37]:
a / b

array([0.        , 0.69444444, 1.02040816, 1.171875  , 1.2345679 ])

In [38]:
a / b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

### **Comparison operations**

In [39]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [40]:
# which element is higher or equal to 2
# comparison operation
a >= 2

array([False, False,  True,  True,  True])

In [41]:
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [42]:
# returns a boolean array
a > b

array([False, False,  True,  True,  True])

In [43]:
a[a > b]

array([2, 3, 4])

### **Summariziing operations**

In [44]:
a

array([0, 1, 2, 3, 4])

In [46]:
a.min()

0

In [47]:
a.max()

4

In [48]:
a.sum()

10

In [49]:
a.mean()

2.0

In [50]:
a.std()

1.4142135623730951

In [52]:
n.sum()

35

In [53]:
n.min()

0